services:
  - type: web
    name: e-ACS-front
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        # Substitua pela URL da sua API no Render (ex: https://e-tet-api.onrender.com)
        value: https://e-tet-api.onrender.com
    routes:
      - source: /*
        destination: /index.html
        type: rewrite
